### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by nyanag**

### CODE REVIEW

**Comment by L04DB4L4NC3R** [comment]
[WIP] Do not merge

**Comment by L04DB4L4NC3R** [comment]
@smarter23 add `netlify.toml` file for netlify builds

**Comment by Geek-ubaid** [comment]
@smarter23 fix this [issue](https://github.com/GDGVIT/Github-Org-Dashboard20/pull/1#issuecomment-582626305) so that i can merge this PR. All the builds failed.

**Comment by Geek-ubaid** [comment]
Merged the Initial commit PR

**Pull request merged**
